annodir='/gluster/common/annotation/'
empty_dir='/home/yannickv/proj/konnektor/mmax/'
annodirs={'anna':annodir+'annotation-Anna',
          'sabrina':annodir+'annotation-Sabrina',
          'holger':annodir+'annotation-Holger',
          'steffi':annodir+'annotation-steffi',
          'null':empty_dir}

anno_sets={'waehrend1':['0_waehrend','2_waehrend','3_waehrend','4_waehrend'],
           'nachdem1':['1_nachdem','5_nachdem','8_nachdem','11_nachdem'],
           'waehrend2':['6_waehrend','7_waehrend','9_waehrend','10_waehrend'],
           'nachdem2':['14_nachdem','16_nachdem','18_nachdem','23_nachdem'],
           'nachdem3':['25_nachdem','27_nachdem','29_nachdem','29_nachdem',
                       '31_nachdem','33_nachdem','37_nachdem_x'],
           'waehrend3':['12_waehrend','13_waehrend','15_waehrend',
                        '17_waehrend','19_waehrend','20_waehrend'],
           'waehrend4':['22_waehrend','24_waehrend','26_waehrend',
                        '28_waehrend','30_waehrend','32_waehrend',
                        '36_waehrend_x'],
           'all1':['0_waehrend','2_waehrend','3_waehrend','4_waehrend',
                   '1_nachdem','5_nachdem','8_nachdem','11_nachdem'],
           'all2':['6_waehrend','7_waehrend','9_waehrend','10_waehrend',
                   '14_nachdem','16_nachdem','18_nachdem','23_nachdem'],
           'bevor':['6_bevor','20_bevor'],
           'aberA':['aber_00','aber_01','aber_02','aber_03','aber_04',
                    'aber_05','aber_06','aber_07','aber_08','aber_09'],
           'alsA':['als_00','als_01','als_02','als_03','als_04',
                    'als_05','als_06','als_07','als_08','als_09']}
