pycwb:
  mongodb:
    username: annodb
    password: xanezafo
  corpora:
    nologin: []
    login: [TUEBA4, R6PRE1, R9PRE1, R9PRE3]
    admin: []
  urls:
    tueba: http://tintoretto.sfb.uni-tuebingen.de/taz
  admins: [yannick,verena,wsdgold]
  cwb_registry: /var/lib/wwwrun/cwb/registry
  sense_edit:
    default_annotator: verena
    db: gwn6
germanet:
  gwn6:
    db_server: postgresql://germanet
